services:
  web:
    container_name: web.localhost
    image: node:20-alpine3.18
    ports:
      - 3000:3000
    depends_on:
      - db
      - idp
    volumes:
      - ./web:/app
    tty: true
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - |
        npm install;
        npm run dev;
  idp:
    container_name: idp.localhost
    image: bitnami/keycloak:24
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: bitnami_keycloak
      KEYCLOAK_DATABASE_USER: bn_keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - ./idp/import:/opt/bitnami/keycloak/data/import
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitnami_keycloak
    volumes:
      - ./db/data:/var/lib/postgresql/data
  smtp:
    container_name: smtp.localhost
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
